"""Offline reverse geocoding: a GPS coordinate -> a country name in Spanish.

Everything here is local and read-only:
  * :func:`gps_from_exif` reads the EXIF GPS IFD with Pillow (the file is never
    written).
  * :func:`parse_iso6709` decodes the ``location`` tag ffprobe reports for
    videos (Apple / Android write ISO 6709 there).
  * :class:`CountryResolver` loads ``resources/country_borders.json`` (Natural
    Earth 1:50m, generated by ``scripts/build_country_borders.py``) and does a
    bounding-box prefilter + pure-Python point-in-polygon test. No numpy.

If the dataset is missing or unreadable the resolver degrades to "no country
found" (everything lands in the *no location* folder) rather than failing.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

from app.utils.file_utils import extended_path
from app.utils.logging_setup import get_logger

log = get_logger(__name__)

_DATA_FILE = Path(__file__).resolve().parent.parent / "resources" / "country_borders.json"

_GPS_IFD = 0x8825
_GPS_LAT_REF = 1
_GPS_LAT = 2
_GPS_LON_REF = 3
_GPS_LON = 4


@dataclass(frozen=True, slots=True)
class GeoCoord:
    lat: float
    lon: float

    @property
    def is_valid(self) -> bool:
        return (
            -90.0 <= self.lat <= 90.0
            and -180.0 <= self.lon <= 180.0
            and not (abs(self.lat) < 1e-7 and abs(self.lon) < 1e-7)  # null island
        )


# ---------------------------------------------------------------------------
# extraction
def _dms_to_deg(value) -> float | None:
    try:
        d, m, s = (float(x) for x in value)
    except (TypeError, ValueError):
        return None
    return d + m / 60.0 + s / 3600.0


def gps_from_exif(path: str) -> GeoCoord | None:
    """Best-effort GPS position from a photo's EXIF. ``None`` if absent/unreadable."""
    try:
        with Image.open(extended_path(path)) as img:
            exif = img.getexif()
            gps = exif.get_ifd(_GPS_IFD) if exif else None
    except Exception:
        return None
    if not gps:
        return None

    lat = _dms_to_deg(gps.get(_GPS_LAT))
    lon = _dms_to_deg(gps.get(_GPS_LON))
    if lat is None or lon is None:
        return None
    lat_ref = str(gps.get(_GPS_LAT_REF, "N")).strip().upper()
    lon_ref = str(gps.get(_GPS_LON_REF, "E")).strip().upper()
    if lat_ref.startswith("S"):
        lat = -lat
    if lon_ref.startswith("W"):
        lon = -lon

    coord = GeoCoord(round(lat, 7), round(lon, 7))
    return coord if coord.is_valid else None


_ISO6709_RE = re.compile(r"([+-]\d+(?:\.\d+)?)([+-]\d+(?:\.\d+)?)")


def parse_iso6709(text: str | None) -> GeoCoord | None:
    """Decode an ISO 6709 location string, e.g. ``+37.7857-122.4011+010.000/``.

    This is what ffprobe returns for the QuickTime ``location`` /
    ``com.apple.quicktime.location.ISO6709`` tag.
    """
    if not text:
        return None
    m = _ISO6709_RE.match(text.strip())
    if not m:
        return None
    try:
        coord = GeoCoord(round(float(m.group(1)), 7), round(float(m.group(2)), 7))
    except ValueError:
        return None
    return coord if coord.is_valid else None


# ---------------------------------------------------------------------------
# resolver
def _point_in_ring(x: float, y: float, ring: list[list[float]]) -> bool:
    inside = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i]
        xj, yj = ring[j]
        if (yi > y) != (yj > y):
            x_cross = (xj - xi) * (y - yi) / (yj - yi) + xi
            if x < x_cross:
                inside = not inside
        j = i
    return inside


def _point_in_polygon(x: float, y: float, rings: list[list[list[float]]]) -> bool:
    # even-odd across the exterior ring + any holes
    crossings = 0
    for ring in rings:
        if _point_in_ring(x, y, ring):
            crossings += 1
    return crossings % 2 == 1


def _seg_dist2(px: float, py: float, ax: float, ay: float, bx: float, by: float) -> float:
    """Squared distance (in degrees^2) from P to segment AB."""
    dx, dy = bx - ax, by - ay
    if dx == 0.0 and dy == 0.0:
        return (px - ax) ** 2 + (py - ay) ** 2
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    return (px - (ax + t * dx)) ** 2 + (py - (ay + t * dy)) ** 2


def _dist_to_rings(x: float, y: float, rings: list[list[list[float]]], best2: float) -> float:
    for ring in rings:
        for i in range(len(ring) - 1):
            ax, ay = ring[i]
            bx, by = ring[i + 1]
            d2 = _seg_dist2(x, y, ax, ay, bx, by)
            if d2 < best2:
                best2 = d2
    return best2


# a coordinate this far outside every border still snaps to the nearest country
# (GPS drift / a photo taken from a boat near the coast). ~0.1 deg ~= 11 km.
_SNAP_TOLERANCE_DEG = 0.1


class CountryResolver:
    """Loads the border dataset once and answers :meth:`country_for`."""

    def __init__(self, data_file: Path | str | None = None) -> None:
        self._countries: list[dict] = []
        path = Path(data_file) if data_file else _DATA_FILE
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
            self._countries = payload.get("countries", [])
        except (OSError, ValueError) as exc:
            log.warning("No se pudo cargar el dataset de países (%s): %s", path, exc)

    @property
    def available(self) -> bool:
        return bool(self._countries)

    def country_for(self, coord: GeoCoord | None) -> str | None:
        if coord is None or not coord.is_valid or not self._countries:
            return None
        x, y = coord.lon, coord.lat

        best: tuple[float, str] | None = None
        for country in self._countries:
            w, s, e, n = country["bbox"]
            if not (w <= x <= e and s <= y <= n):
                continue
            for rings in country["polys"]:
                if _point_in_polygon(x, y, rings):
                    area = (e - w) * (n - s)
                    if best is None or area < best[0]:
                        best = (area, country["name"])
                    break
        if best is not None:
            return best[1]

        # No polygon contains the point (coastal city, GPS drift, simplified
        # borders). Snap to the closest border within a small tolerance.
        tol = _SNAP_TOLERANCE_DEG
        nearest: tuple[float, str] | None = None
        for country in self._countries:
            w, s, e, n = country["bbox"]
            if not (w - tol <= x <= e + tol and s - tol <= y <= n + tol):
                continue
            d2 = tol * tol
            for rings in country["polys"]:
                d2 = _dist_to_rings(x, y, rings, d2)
            if d2 < tol * tol and (nearest is None or d2 < nearest[0]):
                nearest = (d2, country["name"])
        return nearest[1] if nearest else None


_resolver: CountryResolver | None = None


def get_resolver() -> CountryResolver:
    """Process-wide lazy singleton (the dataset is ~1 MB of JSON)."""
    global _resolver
    if _resolver is None:
        _resolver = CountryResolver()
    return _resolver
